In [2]:
import  pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
%pip install xgboost

Requirement already satisfied: xgboost in c:\users\aditya rao\anaconda3\lib\site-packages (3.4.0)
Requirement already satisfied: numpy in c:\users\aditya rao\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\aditya rao\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
df=pd.read_csv("random_forest_placement_dataset.csv")
df

    CGPA  Aptitude_Score  Technical_Score  Internship  Placement
0   6.69              76               64           0          0
1   9.28              83               80           1          1
2   8.29              93               63           0          1
3   7.69              76               70           0          0
4   5.70              48               47           1          0
..   ...             ...              ...         ...        ...
95  7.22              53               78           1          0
96  7.35              50               65           0          0
97  6.92              60               74           0          0
98  5.11              73               77           0          0
99  5.49              47               72           1          0

[100 rows x 5 columns]

In [6]:
df.shape

(100, 5)

In [7]:
df.head()

   CGPA  Aptitude_Score  Technical_Score  Internship  Placement
0  6.69              76               64           0          0
1  9.28              83               80           1          1
2  8.29              93               63           0          1
3  7.69              76               70           0          0
4  5.70              48               47           1          0

In [8]:
df.isnull()

     CGPA  Aptitude_Score  Technical_Score  Internship  Placement
0   False           False            False       False      False
1   False           False            False       False      False
2   False           False            False       False      False
3   False           False            False       False      False
4   False           False            False       False      False
..    ...             ...              ...         ...        ...
95  False           False            False       False      False
96  False           False            False       False      False
97  False           False            False       False      False
98  False           False            False       False      False
99  False           False            False       False      False

[100 rows x 5 columns]

In [9]:
df.isnull().sum()

CGPA               0
Aptitude_Score     0
Technical_Score    0
Internship         0
Placement          0
dtype: int64

In [10]:
#feature selection
x=df.drop("Placement",axis=1)
y=df["Placement"]

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
from xgboost import XGBClassifier

In [13]:
model=XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

In [14]:
#train model
model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [15]:
y_pred=model.predict(x_test)

In [16]:
y_pred

array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [17]:
print("Actual value:",y_test)
print("Predicted value:",y_pred)

Actual value: 83    0
53    1
70    1
45    1
44    0
39    0
22    1
80    1
10    0
0     0
18    0
30    0
73    1
33    1
90    0
4     0
76    0
77    0
12    1
31    0
Name: Placement, dtype: int64
Predicted value: [1 1 1 1 0 0 1 1 0 0 1 0 1 1 0 0 0 0 1 0]

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print("Accuracy score:\n",accuracy_score(y_test,y_pred))
print("Confusion matrix:\n",confusion_matrix(y_test,y_pred))
print("classification_report:\n",classification_report(y_test,y_pred))

Accuracy score:
 0.9
Confusion matrix:
 [[10  2]
 [ 0  8]]
classification_report:
               precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.80      1.00      0.89         8

    accuracy                           0.90        20
   macro avg       0.90      0.92      0.90        20
weighted avg       0.92      0.90      0.90        20

Hyperparameter

In [19]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

In [20]:
model=XGBClassifier(random_state=42)

In [21]:
#hyperparameter
param_grid={
    "n_estimator":[50,100,200],
    "learning_rate":[0.01,0.1,0.2],
    "max_depth":[3,5,7]
}

In [38]:
grid_search=GridSearchCV(
    model,
    param_grid,
    cv=5,
    scoring="accuracy"
)

In [25]:
grid_search.fit(x_train,y_train)

c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:53] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:53] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:53] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:35:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:00] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:00] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:07] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:07] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:17] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:17] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:17] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:18] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=True, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_bin=None,
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 5, 7],
                         'n_estimator': [50, 100, 200]},
             scoring='accuracy')

In [26]:
#best parameter
print("Best Parameter:",grid_search.best_params_)

Best Parameter: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimator': 50}

In [27]:
#best score
print("Best Score:",grid_search.best_score_)

Best Score: 0.8375

In [28]:
#best model
best_model=grid_search.best_estimator_

In [29]:
print("Best model:",best_model.fit(x_train,y_train))

c:\Users\ADITYA RAO\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [10:36:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best model: XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimator=50,
              n_estimators=None, n_jobs=None, ...)

In [30]:
best_model

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimator=50,
              n_estimators=None, n_jobs=None, ...)

In [31]:
#prediction
y_pred_best_model=best_model.predict(x_test)

In [32]:
print("Prediction of best model:",y_pred_best_model)

Prediction of best model: [1 1 1 1 0 0 1 1 0 0 1 0 1 1 0 0 0 0 1 0]

In [33]:
#final Accuracy
print("Accuracy of Final Model:",accuracy_score(y_test,y_pred_best_model))

Accuracy of Final Model: 0.9

Accuracy Of RandomForest VS XgBoost

In [34]:
rf_accuracy=accuracy_score(y_test,y_pred)
xgb_accuracy=accuracy_score(y_test,y_pred_best_model)
print("Random Forest Accuracy:",rf_accuracy*100,"%")
print("XgBoost Accuracy:",xgb_accuracy*100,"%")

Random Forest Accuracy: 90.0 %
XgBoost Accuracy: 90.0 %

In [35]:
from sklearn.metrics import classification_report, confusion_matrix

print("Random Forest")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

print("XGBoost")
print(confusion_matrix(y_test, y_pred_best_model))
print(classification_report(y_test, y_pred_best_model))

Random Forest
[[10  2]
 [ 0  8]]
              precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.80      1.00      0.89         8

    accuracy                           0.90        20
   macro avg       0.90      0.92      0.90        20
weighted avg       0.92      0.90      0.90        20

XGBoost
[[10  2]
 [ 0  8]]
              precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.80      1.00      0.89         8

    accuracy                           0.90        20
   macro avg       0.90      0.92      0.90        20
weighted avg       0.92      0.90      0.90        20

In [36]:
#prediction of new data
new_student=[[8.2,85,70,1]]
prediction=best_model.predict(new_student)

In [37]:
print("Prediction of New Student:",prediction)
if prediction==1:
    print("Placed")
else:
    print("Not Placed")

Prediction of New Student: [1]
Placed